FROM node:18-alpine AS builder
WORKDIR /app
COPY frontend/package*.json .
RUN npm ci
COPY ./frontend .
RUN npm run build

FROM python:3.11-slim
WORKDIR /code
COPY ./requirements.txt .
RUN pip install --no-cache-dir --upgrade -r requirements.txt
COPY . .
COPY --from=builder /app/build/static /code/static
EXPOSE 8000
ENTRYPOINT ["bash", "/code/docker-entrypoint.prod.sh"]
