version: "3.9"

services:
  nginx:
    image: jonasal/nginx-certbot:latest
    container_name: nginx-service
    restart: unless-stopped
    env_file:
      - ./nginx/nginx-certbot.env
    ports:
      - 80:80
      - 443:443
    volumes:
      - static_volume:/code/static
      - media_volume:/code/portfolio/data/media
      - nginx_secrets:/etc/letsencrypt
      - ./nginx/user_conf.d:/etc/nginx/user_conf.d

  django-react-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    entrypoint: bash /frontend/docker-entrypoint.local.sh
    container_name: django-react-frontend
    image: django-react-frontend
    volumes:
      - ./frontend:/frontend
    ports:
      - 3000:3000
    healthcheck:
      test: "curl -f http://localhost:3000"
      interval: 3s
      timeout: 5s
      retries: 5

  django-react-backend:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: bash /code/docker-entrypoint.local.sh
    container_name: django-react-backend
    image: django-react-backend
    volumes:
      - .:/code
      - ../django-react-backend-logs:/logs
      - static_volume:/code/static
      - media_volume:/code/portfolio/data/media
      - nginx_secrets:/etc/letsencrypt
    ports:
      - 8000:8000
    env_file: .env

volumes:
  static_volume:
  media_volume:
  nginx_secrets:
